dist:
  name: otlpeek-collector
  description: OpenTelemetry Collector with otlpeek exporter
  output_path: ./cmd/otlpeek-collector
  version: 0.1.0

receivers:
  - gomod: go.opentelemetry.io/collector/receiver/otlpreceiver v0.126.0

processors:
  - gomod: go.opentelemetry.io/collector/processor/batchprocessor v0.126.0

exporters:
  - gomod: github.com/krisztianfekete/otlpeek v0.0.0
    path: ./ 