receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otlpeek:
    endpoint: ":8080"

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlpeek]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlpeek]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlpeek]

  telemetry:
    logs:
      level: debug
    metrics:
      level: debug